-- 코드를 입력하세요
# SELECT JOIN_TABLE.AO_ID ANIMAL_ID, NAME
# FROM (
#     SELECT AI.ANIMAL_ID AS AI_ID, AO.ANIMAL_ID AS AO_ID, AO.NAME
#     FROM ANIMAL_INS AI
#     RIGHT OUTER JOIN ANIMAL_OUTS AO
#     ON AI.ANIMAL_ID = AO.ANIMAL_ID
#     HAVING AI_ID IS NULL
# ) AS JOIN_TABLE

SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
LEFT OUTER JOIN
ANIMAL_INS AI
ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID