-- 코드를 입력하세요
SELECT COMPANY.CAR_ID, COMPANY.CAR_TYPE, SUM(COMPANY.DAILY_FEE * ((100 - PLAN.DISCOUNT_RATE) / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR COMPANY
INNER JOIN
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING CAR_ID||'_'||COUNT(*) IN
    (
        SELECT CAR_ID||'_'||COUNT(*)
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE < TO_DATE('20221101', 'YYYY-MM-DD')
        OR START_DATE > TO_DATE('20221130', 'YYYY-MM-DD')
        GROUP BY CAR_ID
    )
) HISTORY
ON HISTORY.CAR_ID = COMPANY.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON PLAN.CAR_TYPE = COMPANY.CAR_TYPE
AND PLAN.DURATION_TYPE = '30일 이상'
WHERE (COMPANY.CAR_TYPE = 'SUV'
OR COMPANY.CAR_TYPE = '세단')
GROUP BY COMPANY.CAR_ID, COMPANY.CAR_TYPE
HAVING SUM(COMPANY.DAILY_FEE * ((100 - PLAN.DISCOUNT_RATE) / 100) * 30) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, COMPANY.CAR_TYPE, COMPANY.CAR_ID DESC