-- 코드를 입력하세요
# SELECT COUNT(*) AS CAT,(
#     SELECT COUNT(*)
#     FROM ANIMAL_INS
#     WHERE ANIMAL_TYPE = 'Dog'
# ) AS Dog
# FROM ANIMAL_INS
# WHERE ANIMAL_TYPE = 'Cat'

SELECT ANIMAL_TYPE, COUNT(*)
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY FIELD(ANIMAL_TYPE, 'CAT', 'DOG')