-- 코드를 입력하세요

# SELECT CAST(YEAR(SALES_DATE) AS UNSIGNED) AS YEAR, MONTH(SALES_DATE) AS MONTH,
# COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS,
# ROUND((COUNT(DISTINCT O.USER_ID) / 
# (
#     SELECT COUNT(*)
#     FROM USER_INFO
#     WHERE YEAR(JOINED) = 2021
# )), 1
#       ) AS PUCHASED_RATIO
      
# FROM ONLINE_SALE AS O

# INNER JOIN
# (
#     SELECT USER_ID
#     FROM USER_INFO
#     WHERE YEAR(JOINED) = 2021
# ) AS I
# ON I.USER_ID = O.USER_ID

# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY YEAR, MONTH



SELECT CAST(YEAR(SALES_DATE) AS UNSIGNED) AS YEAR, MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS,
ROUND((COUNT(DISTINCT O.USER_ID) / 
(
    SELECT COUNT(*)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)), 1
      ) AS PUCHASED_RATIO
      
FROM ONLINE_SALE AS O, USER_INFO AS I
WHERE O.USER_ID = I.USER_ID
AND YEAR(I.JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH