-- 코드를 입력하세요
SELECT HALF.FLAVOR
FROM FIRST_HALF HALF
INNER JOIN (SELECT FLAVOR FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = 'fruit_based') INFO
ON INFO.FLAVOR = HALF.FLAVOR
WHERE TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC
