-- 코드를 입력하세요
WITH T AS (
    SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) >= 8
    GROUP BY CAR_ID, MONTH(START_DATE)
)
SELECT MONTH, CAR_ID, RECORDS
FROM T
WHERE CAR_ID IN (SELECT CAR_ID FROM T GROUP BY CAR_ID HAVING SUM(RECORDS) >= 5)
ORDER BY MONTH, CAR_ID DESC

