-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME WHERE HOUR < 23
)
SELECT TIME.HOUR AS HOUR, 0 AS COUNT FROM TIME
WHERE TIME.HOUR NOT IN (SELECT HOUR(DATETIME) FROM ANIMAL_OUTS GROUP BY HOUR(DATETIME))
UNION ALL
SELECT HOUR(DATETIME)AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS 
GROUP BY HOUR(DATETIME)
ORDER BY HOUR

# SELECT HOUR, 0 AS COUNT FROM TIME
# WHERE HOUR NOT IN (SELECT HOUR(DATETIME) FROM ANIMAL_OUTS
# GROUP BY HOUR(DATETIME)
# )
# UNION ALL
# SELECT HOUR(DATETIME), COUNT(*) FROM ANIMAL_OUTS
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR

# SELECT 0 AS HOUR, 0
# UNION ALL
# SELECT 1 AS HOUT, HOUR(DATETIME) FROM ANIMAL_OUTS 