-- 코드를 입력하세요

SELECT
    B.WRITER_ID AS USER_ID, MAX(U.NICKNAME) AS NICKNAME, MAX(U.CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2) AS 전체주소
    , MAX(SUBSTR(U.TLNO, 1, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(*) > 2
ORDER BY B.WRITER_ID DESC

