-- 코드를 입력하세요

# SELECT FH.FLAVOR
# FROM FIRST_HALF FH
# RIGHT JOIN
# (
# SELECT J.FLAVOR, SUM(TOTAL_ORDER) T
# FROM JULY J
# GROUP BY FLAVOR
# ) J
# ON FH.FLAVOR = J.FLAVOR
# ORDER BY T DESC
# LIMIT 3

SELECT TOTAL.FLAVOR
FROM (SELECT FLAVOR, TOTAL_ORDER FROM JULY
UNION ALL
SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF) AS TOTAL
GROUP BY TOTAL.FLAVOR
ORDER BY SUM(TOTAL.TOTAL_ORDER) DESC
LIMIT 3

# SELECT J.FLAVOR, SUM(TOTAL_ORDER) T
# FROM JULY J
# GROUP BY FLAVOR
# ORDER BY T DESC

