# SELECT FLAVOR
# FROM (
# SELECT *
# FROM FIRST_HALF
# UNION ALL
# SELECT *
# FROM JULY
# ) TOTAL
# GROUP BY TOTAL.FLAVOR
# ORDER BY SUM(TOTAL.TOTAL_ORDER) DESC
# LIMIT 3

SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
LEFT JOIN
(
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS J
ON FH.FLAVOR = J.FLAVOR
ORDER BY FH.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3