-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(BS.SALES)
FROM BOOK B, BOOK_SALES BS
WHERE TO_CHAR(BS.SALES_DATE, 'YYYY') = '2022'
AND SUBSTR(TO_CHAR(BS.SALES_DATE, 'YYYYMM'), 5, 2) = '01'
AND BS.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY