-- 코드를 입력하세요
-- SELECT A.AUTHOR_ID, A.AUTHOR_NAME, MAX(CATEGORY), (B.PRICE * BS.SALES) AS TOTAL_SALES
-- FROM BOOK B
-- INNER JOIN AUTHOR A
-- ON A.AUTHOR_ID = B.AUTHOR_ID
-- INNER JOIN BOOK_SALES BS
-- ON BS.BOOK_ID = B.BOOK_ID
-- GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, (B.PRICE * BS.SALES)

-- SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
-- FROM
-- (
--     SELECT  B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE * BS.SALES AS TOTAL_SALES
--     FROM BOOK B
--     INNER JOIN BOOK_SALES BS
--     ON BS.BOOK_ID = B.BOOK_ID
--     AND TO_CHAR(BS.SALES_DATE, 'YYYYMM') = '202201'
--     INNER JOIN AUTHOR A
--     ON A.AUTHOR_ID = B.AUTHOR_ID
--     GROUP BY B.BOOK_ID, B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE * BS.SALES
-- )
-- GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
-- ORDER BY AUTHOR_ID, CATEGORY DESC

WITH TEMP_T AS (
    SELECT  B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
    FROM BOOK B
    INNER JOIN BOOK_SALES BS
    ON BS.BOOK_ID = B.BOOK_ID
    AND TO_CHAR(BS.SALES_DATE, 'YYYYMM') = '202201'
    INNER JOIN AUTHOR A
    ON A.AUTHOR_ID = B.AUTHOR_ID
    GROUP BY B.BOOK_ID, B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
)
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM TEMP_T
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC


    -- SELECT  B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
    -- FROM BOOK B
    -- INNER JOIN BOOK_SALES BS
    -- ON BS.BOOK_ID = B.BOOK_ID
    -- AND TO_CHAR(BS.SALES_DATE, 'YYYYMM') = '202201'
    -- INNER JOIN AUTHOR A
    -- ON A.AUTHOR_ID = B.AUTHOR_ID
    -- WHERE A.AUTHOR_ID = 1
    -- AND B.CATEGORY = '인문'
    -- GROUP BY B.BOOK_ID, B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY

