-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (P.PRICE * S.COUNT) AS SALES
FROM PRODUCT AS P
INNER JOIN
(
    SELECT SUM(SALES_AMOUNT) AS COUNT, PRODUCT_ID FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS S
ON S.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_cODE