SELECT CAR_ID, MAX(AVAILABILITY) AS AVAILABILITY FROM
(
SELECT CAR_ID, '대여중' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= TO_DATE('2022-10-16', 'YYYY-MM-DD')
AND END_DATE >= TO_DATE('2022-10-16', 'YYYY-MM-DD')
GROUP BY CAR_ID
UNION ALL
SELECT CAR_ID, '대여 가능' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE END_DATE < TO_DATE('2022-10-16', 'YYYY-MM-DD')
GROUP BY CAR_ID
ORDER BY CAR_ID DESC, AVAILABILITY DESC
)
GROUP BY CAR_ID
ORDER BY CAR_ID DESC

