-- 코드를 입력하세요
SELECT AP.APNT_NO, P.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP
INNER JOIN PATIENT P
ON P.PT_NO = AP.PT_NO
INNER JOIN DOCTOR D
ON D.DR_ID = AP.MDDR_ID
WHERE DATE_FORMAT(AP.APNT_YMD, '%Y%m%d') = '20220413'
AND AP.APNT_CNCL_YN = 'N'
ORDER BY AP.APNT_YMD
