-- 코드를 입력하세요
# SELECT B.BOOK_ID, A.AUTHOR_NAME, B.PUBLISHED_DATE
# FROM AUTHOR AS A
# RIGHT JOIN
# (
# SELECT BOOK_ID, AUTHOR_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
# FROM BOOK
# WHERE CATEGORY = '경제'
# ) AS B
# ON A.AUTHOR_ID = B.AUTHOR_ID
# ORDER BY B.PUBLISHED_DATE ASC

SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B
JOIN
(
    SELECT AUTHOR_ID, AUTHOR_NAME
    FROM AUTHOR
) AS A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE