-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(R.SCORE, 2) AS SCORE
FROM REST_INFO AS I
INNER JOIN (SELECT REST_ID, AVG(REVIEW_SCORE) AS SCORE FROM REST_REVIEW GROUP BY REST_ID) AS R
ON R.REST_ID = I.REST_ID
WHERE I.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC