-- 코드를 입력하세요
SELECT
    MEMBER_ID
    , MEMBER_NAME
    , GENDER
    , TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD')
FROM MEMBER_PROFILE 
WHERE TLNO IS NOT NULL
AND GENDER = 'W'
AND SUBSTR(DATE_OF_BIRTH, 4, 3) = 'MAR'
ORDER BY MEMBER_ID